version: '3.4'
services:
  image-db:
    image: mysql:8.0
    volumes:
      - image-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_ja_0900_as_cs --log-bin=postdb.bin
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: image_DB
      TZ: Asia/Tokyo　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　
    ports:
      - "9306:3306"

  image:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - ~/Downloads/fishapp-279608-ca691d887e0d.json:/fishapp-279608-ca691d887e0d.json
      - ./images:/images
    depends_on:
      - image-db
    environment:
      TZ: Asia/Tokyo
      GOOGLE_APPLICATION_CREDENTIALS: /fishapp-279608-ca691d887e0d.json

volumes:
  image-data:
  
networks:
  default:
    external:
      name: fishapp-net
